baseURL = 'https://caveli.us/'
languageCode = 'en-us'
title = 'caveli.us'
[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
[asset]
  js = ["js/lastfm-tracker.js"]

[security]
  [security.http]
    mediaTypes = ["application/javascript"]
    # Allow LastFM API calls
    [security.http.directives]
      connectSrc = ["'self'", "ws.audioscrobbler.com"]
