baseURL = 'https://caveli.us/'
languageCode = 'en-us'
title = 'caveli.us'
timezone = "Europe/Paris"
[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
[asset]
  js = ["js/lastfm-tracker.js"]
[security]
  [security.http]
    mediaTypes = ["application/javascript"]
    # Allow LastFM API calls
    [security.http.directives]
      connectSrc = ["'self'", "ws.audioscrobbler.com"]
[params]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

lastfm_api_key = "$LASTFM_API_KEY"

